# Generated by Django 4.2.3 on 2023-10-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("crest", models.CharField(blank=True, max_length=200)),
                ("banner_image", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("founded_in", models.PositiveIntegerField(blank=True, null=True)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("rank", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("league", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("try", "Try Scored"),
                            ("card", "Card Given"),
                            ("conversion", "Conversion"),
                        ],
                        max_length=10,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                ("player", models.CharField(max_length=100)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="teams.match",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team1",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team2",
                to="teams.team",
            ),
        ),
    ]
