# Generated by Django 4.2.3 on 2023-10-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "verbose_name": "Rugby Team",
                "verbose_name_plural": "Rugby Teams",
            },
        ),
    ]
