# Generated by Django 4.2.3 on 2023-11-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("try", "Try Scored"),
                    ("yellow_card", "Yellow Card Given"),
                    ("red_card", "Red Card Given"),
                    ("try_conversion", "Try Conversion"),
                    ("penalty_conversion", "Penalty Conversion"),
                ],
                max_length=18,
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("position", models.CharField(max_length=50)),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                ("speed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("strength", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("agility", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("endurance", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tackling", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("passing", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("kicking", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "bronco_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "sprint_10m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "sprint_40m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("broad_jump", models.PositiveIntegerField(blank=True, null=True)),
                ("chin_ups", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("back_squat", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "trap_bar_deadlift",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rugby Player",
                "verbose_name_plural": "Rugby Players",
            },
        ),
    ]
