# Generated by Django 4.2.3 on 2023-11-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_matchevent_event_type_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("try", "Try Scored"),
                    ("yellow_card", "Yellow Card Given"),
                    ("red_card", "Red Card Given"),
                    ("try_conversion", "Try Conversion"),
                    ("penalty_conversion", "Penalty Conversion"),
                    ("penalty_try", "Penalty Try"),
                ],
                max_length=18,
            ),
        ),
    ]
