# Generated by Django 4.2.3 on 2023-10-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_team_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_score",
            field=models.IntegerField(default=0),
        ),
    ]
