# Generated by Django 4.2.3 on 2023-11-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_matchevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserves",
                    models.ManyToManyField(
                        blank=True, related_name="roster_reserves", to="teams.player"
                    ),
                ),
                (
                    "starting_23",
                    models.ManyToManyField(
                        blank=True, related_name="roster_starting_23", to="teams.player"
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roster",
                "verbose_name_plural": "Rosters",
            },
        ),
    ]
