# Generated by Django 4.2.3 on 2023-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_roster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("PR", "Prop"),
                    ("HK", "Hooker"),
                    ("LK", "Lock"),
                    ("FL", "Flanker"),
                    ("N8", "Number Eight"),
                    ("SH", "Scrum-Half"),
                    ("FH", "Fly-Half"),
                    ("CE", "Center"),
                    ("WI", "Wing"),
                    ("FB", "Full-Back"),
                ],
                max_length=2,
            ),
        ),
    ]
