# Generated by Django 4.2.3 on 2023-11-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_alter_player_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bronco_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
