# Generated by Django 4.2.3 on 2023-11-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_alter_player_bronco_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.player",
            ),
        ),
    ]
