# Generated by Django 4.2.3 on 2023-11-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_team_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
