# Generated by Django 4.2.3 on 2023-11-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapsInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("team_name", models.CharField(max_length=255)),
                ("cap_base_color", models.CharField(max_length=50)),
                ("cap_trim_color", models.CharField(max_length=50)),
                ("cell_phone_number", models.CharField(max_length=15)),
                ("number_of_caps", models.IntegerField()),
            ],
        ),
    ]
