from teams.models import Team

# Create teams for each city with historical descriptions and placeholders
teams_data = [
    {
        'name': 'White Plains',
        'crest': 'white_plains_crest.jpg',
        'banner_image': 'white_plains_banner.jpg',
        'description': 'White Plains, located in Westchester County, New York, has a rich sports history and is known for its active community. The city has been a hub for recreational activities, making it an ideal location for a thriving rugby culture. The White Plains rugby club, established in 1971, can harness the city\'s sporting spirit and grow into a dominant force in the All-American Rugby Cup. With a focus on fitness, community, and local talent, they can captivate fans with their commitment to rugby excellence.',
        'founded_in': 1971,
        'state': 'New York',
        'city': 'White Plains',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'New York City',
        'crest': 'nyc_crest.jpg',
        'banner_image': 'nyc_banner.jpg',
        'description': 'New York City is not just a global cultural hub but also a sports epicenter. The city has a rich history in various sports, from baseball at Yankee Stadium to basketball at Madison Square Garden. It\'s a place where sports legends are born. Old Blue, a well-established rugby club in the city, can leverage New York\'s sports legacy to build a dynamic rugby team. With a diverse and passionate fan base, they have the potential to become a powerhouse in the All-American Rugby Cup, attracting attention and talent from across the city.',
        'founded_in': 1980,
        'state': 'New York',
        'city': 'New York',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Philadelphia',
        'crest': 'philly_crest.jpg',
        'banner_image': 'philly_banner.jpg',
        'description': 'Philadelphia has a vibrant sports culture and is known for passionate fans. It\'s home to iconic sports teams, like the Philadelphia Eagles (NFL) and the Philadelphia 76ers (NBA). Philly United can tap into the city\'s sports enthusiasm and passionate fan base. They can become the pride of Philadelphia by embodying the city\'s competitive spirit and adding rugby to its list of iconic teams.',
        'founded_in': 1975,
        'state': 'Pennsylvania',
        'city': 'Philadelphia',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Pittsburgh',
        'crest': 'pittsburgh_crest.jpg',
        'banner_image': 'pittsburgh_banner.jpg',
        'description': 'Pittsburgh is a city deeply rooted in sports, most notably for its NFL team, the Pittsburgh Steelers. The city\'s history is filled with legendary athletes and devoted sports fans. Pittsburgh\'s rugby team can aspire to the same level of sportsmanship and dedication that characterizes the city\'s teams. With a determined approach, they can become a formidable presence in the All-American Rugby Cup, attracting fans and talent from the city known for its passion for sports.',
        'founded_in': 1985,
        'state': 'Pennsylvania',
        'city': 'Pittsburgh',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Harrisburg',
        'crest': 'harrisburg_crest.jpg',
        'banner_image': 'harrisburg_banner.jpg',
        'description': 'Harrisburg has a strong sports community, with a history of local sports clubs and events. The city\'s passion for sports extends to its recreational facilities and fields. A team representing Harrisburg can leverage the city\'s sporting infrastructure and enthusiastic community to grow their rugby presence. By creating a welcoming and supportive environment, they can become a focal point for local athletes and fans.',
        'founded_in': 1990,
        'state': 'Pennsylvania',
        'city': 'Harrisburg',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Annapolis',
        'crest': 'annapolis_crest.jpg',
        'banner_image': 'annapolis_banner.jpg',
        'description': 'Annapolis is home to the United States Naval Academy, and its sporting traditions are intertwined with military discipline. It has a history of producing skilled athletes and leaders. A team from Annapolis can adopt the principles of leadership, teamwork, and commitment to excellence associated with the Naval Academy. They can draw from the city\'s disciplined approach to sports and develop a rugby team with strong core values.',
        'founded_in': 1983,
        'state': 'Maryland',
        'city': 'Annapolis',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Loudoun',
        'crest': 'loudoun_crest.jpg',
        'banner_image': 'loudoun_banner.jpg',
        'description': 'Loudoun County, Virginia, is not only known for its scenic beauty but also for a vibrant sports culture, with a strong emphasis on youth sports development. Loudoun\'s rugby team can be a testament to the county\'s commitment to sports development. By nurturing young talent and fostering a love for rugby, they can become a growing force in the All-American Rugby Cup, attracting families and sports enthusiasts from the region.',
        'founded_in': 1995,
        'state': 'Virginia',
        'city': 'Loudoun',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Northern Virginia',
        'crest': 'northern_va_crest.jpg',
        'banner_image': 'northern_va_banner.jpg',
        'description': 'Northern Virginia, with its proximity to Washington, D.C., has a history of competitive sports and a diverse population that contributes to its vibrant sports scene. A team representing Northern Virginia can harness the city\'s diversity and competitive spirit to develop a rugby team that reflects the region\'s sporting legacy. By emphasizing inclusivity and a strong work ethic, they can compete at a high level in the tournament.',
        'founded_in': 2000,
        'state': 'Virginia',
        'city': 'Northern Virginia',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Norfolk',
        'crest': 'norfolk_crest.jpg',
        'banner_image': 'norfolk_banner.jpg',
        'description': 'Norfolk, Virginia, has a strong sports tradition, with a focus on youth sports development and the nurturing of local talent. The Norfolk Blues-themed team can draw inspiration from the city\'s commitment to sports development. They can be known for their youth programs and emphasis on teamwork, becoming a hub for aspiring rugby players in Norfolk.',
        'founded_in': 2005,
        'state': 'Virginia',
        'city': 'Norfolk',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Raleigh',
        'crest': 'raleigh_crest.jpg',
        'banner_image': 'raleigh_banner.jpg',
        'description': 'Raleigh, North Carolina, is a city with a growing sports culture. It is home to several collegiate teams and has seen a surge in sports-related events and activities. A team from Raleigh can capitalize on the city\'s budding sports scene. They can become a dynamic presence in the All-American Rugby Cup, attracting local talent and fans by participating actively in the city\'s sports development initiatives.',
        'founded_in': 2010,
        'state': 'North Carolina',
        'city': 'Raleigh',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Nashville',
        'crest': 'nashville_crest.jpg',
        'banner_image': 'nashville_banner.jpg',
        'description': 'Nashville, Tennessee, is famous for its music scene, but it\'s also home to a thriving sports community, including NFL\'s Tennessee Titans and NHL\'s Nashville Predators. A Nashville rugby team can complement the city\'s entertainment culture with sports excitement. By tapping into the city\'s vibrant atmosphere and community engagement, they can offer an entertaining and thrilling rugby experience for fans.',
        'founded_in': 2015,
        'state': 'Tennessee',
        'city': 'Nashville',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Life - Atlanta',
        'crest': 'atlanta_crest.jpg',
        'banner_image': 'atlanta_banner.jpg',
        'description': 'Atlanta, Georgia, is a hub for sports, with a rich history in baseball, football, and golf. It\'s home to iconic venues like Turner Field and the Masters Golf Tournament. A team representing Life University in Atlanta can benefit from the city\'s sports legacy. By adopting a competitive spirit and commitment to excellence, they can establish themselves as a prominent rugby team in Atlanta\'s sporting landscape.',
        'founded_in': 2017,
        'state': 'Georgia',
        'city': 'Atlanta',
        'league': 'All-American Rugby Cup',
    },
    {
        'name': 'Charlotte',
        'crest': 'charlotte_crest.jpg',
        'banner_image': 'charlotte_banner.jpg',
        'description': 'Charlotte, North Carolina, is a city with a growing sports culture, anchored by the Charlotte Hornets (NBA) and the Carolina Panthers (NFL). Charlotte\'s rugby team can embrace the city\'s dynamic sports culture and community engagement. By actively participating in local sports events and initiatives, they can garner support and become a beloved addition to Charlotte\'s sporting scene.',
        'founded_in': 2020,
        'state': 'North Carolina',
        'city': 'Charlotte',
        'league': 'All-American Rugby Cup',
    },
]

# Create teams in the database
for data in teams_data:
    Team.objects.create(**data)
