# Generated by Django 4.2.3 on 2023-10-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "hosted_by",
                    models.CharField(default="First Five Rugby", max_length=50),
                ),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "register_link",
                    models.CharField(
                        default="https://firstfiverugby.com/camps", max_length=100
                    ),
                ),
                (
                    "logo_url",
                    models.CharField(
                        default="https://i.imgur.com/chO9gOg.png", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pathways", "Pathways"),
                            ("festival", "Festival"),
                            ("camp", "Camp"),
                        ],
                        default="camp",
                        max_length=20,
                    ),
                ),
                ("external_registration", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_full_name", models.CharField(max_length=100)),
                ("player_age", models.PositiveIntegerField()),
                ("player_grade", models.CharField(max_length=50)),
                ("parent_full_name", models.CharField(max_length=100)),
                ("parent_email", models.EmailField(max_length=254)),
                ("risk_checkbox", models.BooleanField()),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="f5.event"
                    ),
                ),
            ],
        ),
    ]
