# Generated by Django 4.2.2 on 2023-07-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f5', '0002_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='images',
        ),
        migrations.RemoveField(
            model_name='f5user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='f5user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='Camp',
        ),
        migrations.DeleteModel(
            name='CampImage',
        ),
        migrations.DeleteModel(
            name='F5user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
