# Generated by Django 4.2.3 on 2023-11-07 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("f5", "0002_alter_eventticket_player_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coached_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
