# Generated by Django 4.2.3 on 2023-09-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0002_match"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Match",
            new_name="Fixture",
        ),
    ]
