# Generated by Django 4.2.3 on 2023-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0003_rename_match_fixture"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="score_team_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fixture",
            name="score_team_2",
            field=models.IntegerField(default=0),
        ),
    ]
