# Generated by Django 4.2.3 on 2023-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0004_fixture_score_team_1_fixture_score_team_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="region",
            field=models.CharField(default="usa", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="zipcode",
            field=models.CharField(default="00000", max_length=100),
        ),
    ]
