# Generated by Django 4.2.3 on 2023-11-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0004_capsinquiry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CapsInquiry",
        ),
    ]
