# Generated by Django 4.2.3 on 2023-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0005_team_region_team_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image_url",
            field=models.CharField(default="image.png", max_length=100),
        ),
    ]
