# Generated by Django 4.2.3 on 2023-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0006_team_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="register_url",
            field=models.CharField(default="usarugby.com", max_length=100),
        ),
    ]
