# Generated by Django 4.2.3 on 2023-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0010_team_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.CharField(default="open", max_length=100),
        ),
    ]
