# Generated by Django 4.2.3 on 2023-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0011_team_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image_url",
            field=models.CharField(default="https://shorturl.at/krW01", max_length=100),
        ),
    ]
