# Generated by Django 4.2.3 on 2023-09-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0013_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="m", max_length=10),
        ),
    ]
