# Generated by Django 4.2.3 on 2023-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0014_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(default="M", max_length=10),
        ),
    ]
