# Generated by Django 4.2.3 on 2023-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0015_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(default="https://place-hold.it/500", max_length=200),
        ),
    ]
