# Generated by Django 4.2.3 on 2023-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0017_remove_product_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="fixture",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
