# Generated by Django 4.2.3 on 2023-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0018_event_alter_fixture_id_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="team_only",
            field=models.BooleanField(default=False),
        ),
    ]
