# Generated by Django 4.2.3 on 2023-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0019_product_team_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="register_link",
            field=models.CharField(
                default="https://firstfiverugby.com/camps", max_length=100
            ),
        ),
    ]
