# Generated by Django 4.2.3 on 2023-10-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0020_event_register_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logo_url",
            field=models.CharField(
                default="https://i.imgur.com/chO9gOg.png", max_length=100
            ),
        ),
    ]
