# Generated by Django 4.2.3 on 2023-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0022_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hosted_by",
            field=models.CharField(default="First Five Rugby", max_length=50),
        ),
    ]
