# Generated by Django 4.2.3 on 2023-10-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0023_event_hosted_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_full_name", models.CharField(max_length=100)),
                ("player_age", models.PositiveIntegerField()),
                ("player_grade", models.CharField(max_length=50)),
                ("parent_full_name", models.CharField(max_length=100)),
                ("parent_email", models.EmailField(max_length=254)),
                ("risk_checkbox", models.BooleanField()),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="f5.event"
                    ),
                ),
            ],
        ),
    ]
