# Generated by Django 4.2.3 on 2023-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0024_eventticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
