# Generated by Django 4.2.3 on 2023-10-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0025_event_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_url",
            field=models.CharField(default="#", max_length=200),
        ),
    ]
