# Generated by Django 4.2.3 on 2023-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f5", "0026_product_stripe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_registration",
            field=models.BooleanField(default=False),
        ),
    ]
