# Generated by Django 4.2.3 on 2023-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_wrsinqueries"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrsinqueries",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
