# Generated by Django 4.2.3 on 2023-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_wrsinqueries_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="{% static 'product_imags' %}"
            ),
        ),
    ]
