# Generated by Django 4.2.3 on 2023-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstfiveuser",
            name="level",
            field=models.IntegerField(default="0"),
        ),
        migrations.AddField(
            model_name="firstfiveuser",
            name="xp",
            field=models.IntegerField(default="0"),
        ),
    ]
