# Generated by Django 4.2.3 on 2023-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_firstfiveuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstfiveuser",
            name="profile_photo",
            field=models.TextField(
                blank=True, default="https://i.imgur.com/vuKfIWS.png"
            ),
        ),
    ]
