# Generated by Django 4.2.3 on 2023-11-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_firstfiveuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstfiveuser",
            name="profile_photo",
            field=models.CharField(default="https://i.imgur.com/vuKfIWS.png"),
        ),
    ]
