# Generated by Django 4.2.3 on 2023-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalog/static/product_images"
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("event_date", models.DateField()),
                ("event_type", models.CharField(max_length=100)),
                ("event_time", models.CharField(max_length=50)),
                ("home_team", models.CharField(max_length=200)),
                ("away_team", models.CharField(max_length=200)),
                ("home_score", models.IntegerField(default=0)),
                ("away_Score", models.IntegerField(default=0)),
            ],
        ),
    ]
